# Generated by Django 5.0 on 2025-08-24 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('reward', 'Recompensa'), ('daily', 'Tarefa Diária'), ('alert', 'Alerta')], default='info', max_length=20),
        ),
    ]
