# Generated by Django 5.0 on 2025-08-26 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='reward_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('reward', 'Recompensa'), ('reward', 'Tarefa Diária'), ('reward', 'Alerta')], default='info', max_length=20),
        ),
    ]
