# Generated by Django 5.0 on 2025-08-27 01:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_reward_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
