# Generated by Django 5.0 on 2025-09-12 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_remove_notification_date_notification_reward_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('reward', 'Recompensa'), ('', 'Tarefa Diária'), ('random', 'Aleatória'), ('alert', 'Alerta'), ('agent', 'Agente')], default='alert', max_length=50),
        ),
    ]
