# Generated by Django 5.0 on 2025-09-15 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='scheduled_for',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('reward', 'Recompensa'), ('daily', 'Tarefa Diária'), ('random', 'Aleatória'), ('alert', 'Alerta'), ('agent', 'Agente'), ('schedule', 'Agendada')], default='alert', max_length=50),
        ),
    ]
