# Generated by Django 5.0 on 2025-08-24 22:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notifications', '0002_notification_title_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_type', models.CharField(choices=[('xp', 'Experiência (XP)'), ('coin', 'Moeda'), ('item', 'Item'), ('lootbox', 'Caixa Misteriosa'), ('api', 'Chamada de API')], max_length=20)),
                ('amount', models.IntegerField(blank=True, help_text='XP/moeda/quantidade (se aplicável)', null=True)),
                ('item_code', models.CharField(blank=True, help_text='Identificador do item (se aplicável)', max_length=100, null=True)),
                ('mission_code', models.CharField(blank=True, help_text='Ligação opcional com missão', max_length=100, null=True)),
                ('api_endpoint', models.CharField(blank=True, help_text='Endpoint de API (se aplicável)', max_length=255, null=True)),
                ('extra_data', models.JSONField(blank=True, default=dict, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('granted', 'Concedida'), ('claimed', 'Resgatada')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('granted_at', models.DateTimeField(blank=True, null=True)),
                ('notification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rewards', to='notifications.notification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
