# Generated by Django 5.0 on 2025-09-03 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reward',
            name='api_endpoint',
        ),
        migrations.RemoveField(
            model_name='reward',
            name='mission_code',
        ),
        migrations.RemoveField(
            model_name='reward',
            name='notification',
        ),
        migrations.AlterField(
            model_name='reward',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reward',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='reward',
            name='item_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reward',
            name='reward_type',
            field=models.CharField(choices=[('xp', 'Experiência (XP)'), ('vitalidade', 'Vitalidade'), ('coin', 'Moeda'), ('item', 'Item'), ('lootbox', 'Caixa Misteriosa'), ('api', 'Chamada de API')], max_length=20),
        ),
        migrations.AlterField(
            model_name='reward',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='reward',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
