# Generated by Django 5.0 on 2025-09-03 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0002_remove_reward_api_endpoint_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='reward_type',
            field=models.CharField(choices=[('xp', 'XP'), ('coin', 'Moeda'), ('item', 'Item'), ('lootbox', 'Lootbox'), ('api', 'API')], max_length=20),
        ),
    ]
