# Generated by Django 5.0 on 2025-09-04 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_remove_notification_date_notification_reward_count_and_more'),
        ('rewards', '0003_alter_reward_reward_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='notification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notifications.notification'),
        ),
    ]
