# Generated by Django 5.0 on 2025-09-12 15:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_alter_notification_notification_type'),
        ('rewards', '0004_reward_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='reward_type',
            field=models.CharField(choices=[('xp', 'XP'), ('vitality', 'Vitalidade'), ('coin', 'Moeda'), ('item', 'Item'), ('lootbox', 'Lootbox'), ('api', 'API')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='reward',
            constraint=models.UniqueConstraint(fields=('user', 'notification', 'reward_type'), name='unique_reward_per_type_per_notification'),
        ),
    ]
