# Generated by Django 5.0 on 2025-07-24 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tipo_conta',
            field=models.CharField(choices=[('estudante', 'Estudante'), ('empresa', 'Empresa'), ('admin', 'Admin')], default='estudante', max_length=20),
        ),
    ]
