# Generated by Django 5.0 on 2025-09-03 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0003_profile_coins_profile_vitality_profile_xp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='coins',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='vitality',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='xp',
        ),
    ]
